language: java
# use Java 8
jdk:
- oraclejdk8

before_install:
- chmod +x gradlew

dist: trusty

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
