language: java
# use Java 14
jdk: openjdk14

dist: trusty

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle